name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 123456
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Start app
        shell: bash
        run: |
          nohup java -jar target/quarkus-app/quarkus-run.jar & sleep 10s
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: collections/api-test.js
